### ISSUE TITLE
Undefined symbols for arm64

### ISSUE THREAD

**Issue by Daxziz** [Izhido/Quake_For_OSX#1]
Hi

Just downloaded the source and tried to compile it for the latest version of tvos.
I get the following error message when I try to compile it. I hope you can help me out with whatever went wrong.

Undefined symbols for architecture arm64:
  "_net_drivers", referenced from:
      _Slist_Send in net_main.o
      _Slist_Poll in net_main.o
      _NET_Connect in net_main.o
      _NET_CheckNewConnections in net_main.o
      _NET_Close in net_main.o
      _NET_GetMessage in net_main.o
      _NET_SendMessage in net_main.o
      ...
  "_volume", referenced from:
      _M_AdjustSliders in menu.o
      _M_Options_Draw in menu.o
  "_S_ClearBuffer", referenced from:
      _SCR_ModalMessage in screen.o
  "_net_numdrivers", referenced from:
      _Slist_Send in net_main.o
      _Slist_Poll in net_main.o
      _NET_Connect in net_main.o
      _NET_CheckNewConnections in net_main.o
      _NET_Init in net_main.o
      _NET_Listen_f in net_main.o
  "_S_Init", referenced from:
      _Host_Init in host.o
  "_S_ExtraUpdate", referenced from:
      _Draw_FadeScreen in draw.o
      _M_Draw in menu.o
      _R_ScanEdges in r_edge.o
      _R_EdgeDrawing in r_main.o
      _R_RenderView_ in r_main.o
  "_S_StaticSound", referenced from:
      _CL_ParseStaticSound in cl_parse.o
  "_S_EndPrecaching", referenced from:
      _CL_ParseServerInfo in cl_parse.o
  "_S_PrecacheSound", referenced from:
      _CL_ParseServerInfo in cl_parse.o
      _CL_InitTEnts in cl_tent.o
  "_S_LocalSound", referenced from:
      _Con_Print in console.o
      _M_Main_Key in menu.o
      _M_SinglePlayer_Key in menu.o
      _M_Load_Key in menu.o
      _M_Save_Key in menu.o
      _M_MultiPlayer_Key in menu.o
      _M_Setup_Key in menu.o
      ...
  "_bgmvolume", referenced from:
      _M_AdjustSliders in menu.o
      _M_Options_Draw in menu.o
  "_S_TouchSound", referenced from:
      _CL_ParseServerInfo in cl_parse.o
  "_S_BeginPrecaching", referenced from:
      _CL_ParseServerInfo in cl_parse.o
  "_S_StopSound", referenced from:
      _CL_ParseServerMessage in cl_parse.o
  "_S_Update", referenced from:
      __Host_Frame in host.o
  "_S_StartSound", referenced from:
      _CL_ParseStartSoundPacket in cl_parse.o
      _CL_ParseTEnt in cl_tent.o
  "_S_StopAllSounds", referenced from:
      _CL_Disconnect in cl_main.o
      _SCR_BeginLoadingPlaque in screen.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Izhido** [comment]
Fixed.

I forgot to add a few source files into the tvOS target since the latest changes. You should be able to compile it now with no problems.

Things to notice:

1) You should be getting sound now for the tvOS target. In my very first test with these changes, the sound driver did not initialize correctly. This didn't happen afterwards. Strange. :)
2) The current net code for TCP is failing me at gethostbyname(). Further investigation is needed to find out what's going on. For the moment, I'm using the loopback driver (== no network) for tvOS.
3) Playing by using the Siri remote is really, really, really, REALLY frustrating. I'd love to add support for standard game controllers at some point - that, however, will have to wait until I get proper hardware.

**Comment by Daxziz** [comment]
Sounds good. I'll try compiling it again this weekend from the updated source.

Regarding the controller. If it could be playable with the controller in landscape mode it would be off to a fair start. I think this is fairly easy to add into the code.

In the normal "remote" position it would be a hell to play or even just test it.

Thanks for all your work so far.

**Comment by Daxziz** [comment]
I've spend a few hours working on the extended gamepad profile.

Currently it discovers the controller and lets you change weapon on "left shoulder" and fire on "button A".
I'll add more later tonight and try to get it to follow Apples requirements.
