### ISSUE TITLE
iOS_VR build fails

### ISSUE THREAD

**Issue by neomanic** [Izhido/Quake_For_OSX#5]
I'm trying to build the iOS_VR version, and haven't been able to get past link errors.

Firstly, it can't seem to build for arm64 (on iPhone 7) as there's only armv7 arch included in the Google Cardboard SDK. This is obviously a Google issue as they haven't released an arm64 lib.

Secondly, once I am forcing an armv7 arch build, it can't find the GVRCardboardView class in libGVRView_arm.a.  (This class is present in `libGVRView_x86.a`, but obviously the wrong arch.)

Podfile.lock:
```
  - GVRSDK (1.10.0):
    - GVRSDK/GVRView (= 1.10.0)
  - GVRSDK/Base (1.10.0)
  - GVRSDK/GVRView (1.10.0):
    - GVRSDK/Base
```

```
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_GVRCardboardView", referenced from:
      objc-class-ref in GameViewController.o
ld: symbol(s) not found for architecture armv7
```

and confirmed with `nm libGVRView_arm.a | grep GVRCardboardView` giving no output.

Is this something you've come across previously?

**Comment by neomanic** [comment]
My mistake... that class symbol isn't in either the ARM or x86 versions, and there is arm64 code in the ARM lib.
I will go back to the beginning and try to work out why it can't link.

**Comment by neomanic** [comment]
So from a fresh install, it just can't find GVRCardboardView in libGVRView_arm.a as per the original post (architecture doesn't matter). And I can't find that symbol using nm. Any thoughts?

**Comment by anuraagdjain** [comment]
Add `pod 'CardboardSDK' ` into your pod file and do `pod install` and then import following into your bridging header

`#import "GCSCardboardView.h"`
`#import "GCSCardboardAudioEngine.h"`
`#import "GCSHeadTransform.h"`
`#import "GCSWidgetView.h"`
`#import "GCSPanoramaView.h"`
`#import "GCSVideoView.h"`

Make sure you remove `pod 'GVRSDK' `from your pod file. This method worked for me on Xcode 8.2.1 Swift 3.0.2

update: Using `pod 'GVRSDK', '1.0.1'` actually solves the issue.

**Comment by neomanic** [comment]
Thanks for your help.

I also removed `#import <GVRCardboardView.h>` from the bridging header.

What do you do with all the missing `GVRCardboardViewDelegate`, `GVRHeadTransform` etc in `GameViewController.swift`?

**Comment by anuraagdjain** [comment]
I've updated my above comment. If you're using CardboardSDK then change `GVR` to `GCS` at all places and errors will be solved.

**Comment by neomanic** [comment]
That got the build working fine... now just have to work out why running it fails. Thanks for your help.

**Comment by Izhido** [comment]
Glad to be of help. 😂😂😂 (Closing.)
